import type { AnyIconName } from '../components/icons/index.js';

/**
 * Semantic UI chrome -> icon names.
 * Values are either Doodle asset keys (`doodle_*`) or Lucide refs (`lu:*`).
 */
export const uiIcons = {
  alertCircle: 'doodle_caution',
  alertTriangle: 'doodle_caution',
  arrowRight: 'lu:chevron-right',
  baby: 'doodle_user',
  bell: 'doodle_bell',
  book: 'doodle_book',
  bookOpen: 'doodle_book_open',
  cake: 'doodle_cake',
  calendar: 'doodle_calendar',
  camera: 'doodle_camera',
  check: 'lu:check',
  checkOk: 'doodle_tick_circle',
  chevronDown: 'lu:chevron-down',
  chevronLeft: 'lu:chevron-left',
  chevronRight: 'lu:chevron-right',
  chevronUp: 'lu:chevron-up',
  circleCheck: 'doodle_tick_circle',
  clipboard: 'doodle_checklist',
  clipboardList: 'doodle_checklist',
  clock: 'doodle_clock',
  close: 'lu:x',
  cookie: 'doodle_cookie',
  download: 'doodle_external',
  edit: 'doodle_pencil',
  externalLink: 'doodle_external',
  eye: 'doodle_eye',
  fileText: 'doodle_file',
  filter: 'doodle_list',
  flame: 'doodle_fire',
  globe: 'doodle_globe',
  grid: 'doodle_grid',
  heart: 'doodle_heart',
  home: 'doodle_home',
  info: 'doodle_info',
  layoutDashboard: 'doodle_dashboard',
  loader: 'lu:loader',
  lock: 'doodle_lock',
  logout: 'doodle_logout',
  mail: 'doodle_mail',
  mapPin: 'doodle_locationpin',
  megaphone: 'doodle_megaphone',
  menu: 'lu:menu',
  messageSquare: 'doodle_message',
  moon: 'doodle_moon',
  music: 'doodle_music',
  phone: 'doodle_phone',
  plus: 'lu:plus',
  send: 'doodle_send',
  share: 'doodle_share',
  shield: 'doodle_shield',
  shieldCheck: 'doodle_shield_check',
  smartphone: 'doodle_phone_smart',
  sparkles: 'doodle_sparkles',
  star: 'doodle_star',
  stopSquare: 'lu:x',
  trash: 'lu:trash',
  user: 'doodle_user',
  users: 'doodle_users',
} as const satisfies Record<string, AnyIconName>;

export type UiIconKey = keyof typeof uiIcons;
