import type { IconName } from '../components/icons/index.js';

/**
 * Semantic UI chrome → asset icon keys (all must exist in iconMap).
 * Prefer importing `appAssetIcons` for product features; use this for generic controls.
 */
export const uiIcons = {
  alertCircle: 'bad_decision',
  alertTriangle: 'disclaimer',
  apple: 'cell_phone',
  arrowRight: 'right',
  arrowUpRight: 'up_right',
  award: 'vip',
  baby: 'contacts',
  bell: 'alarm_clock',
  book: 'reading',
  bookOpen: 'reading_ebook',
  bot: 'assistant',
  /** Bar chart / analytics (LuChartNoAxesColumn). */
  chartColumn: 'chart-growth-invest-svgrepo-com',
  building: 'factory',
  calendar: 'calendar',
  calendarRange: 'timeline',
  camera: 'camera',
  /** Birthday / celebration (LuCake). */
  cake: 'birthday-cake-svgrepo-com',
  check: 'checkmark',
  checkOk: 'ok',
  chevronDown: 'down',
  chevronLeft: 'left',
  chevronRight: 'right',
  chevronUp: 'up',
  clipboard: 'todo_list',
  /** List / backlog (LuClipboardList). */
  clipboardList: 'todo_list',
  clock: 'clock-svgrepo-com',
  /** LuCircleCheck-style status. */
  circleCheck: 'ok',
  /** LuCircleAlert-style status. */
  circleAlert: 'bad_decision',
  close: 'cancel',
  cloudUpload: 'upload',
  cookie: 'template',
  download: 'download',
  edit: 'edit_image',
  externalLink: 'external',
  eye: 'view_details',
  fileText: 'file',
  files: 'document',
  filter: 'filled_filter',
  flame: 'positive_dynamic',
  gift: 'donate',
  globe: 'globe-svgrepo-com',
  graduationCap: 'graduation_cap',
  grid: 'grid',
  grip: 'serial_tasks',
  heart: 'like',
  help: 'questions',
  home: 'home',
  hourglass: 'clock',
  image: 'add_image',
  info: 'info',
  layoutDashboard: 'statistics',
  leaf: 'biomass',
  /** Hyperlink (LuLink). */
  link: 'link',
  library: 'library',
  layers: 'workflow',
  lightbulb: 'idea',
  list: 'list',
  loader: 'synchronize',
  lock: 'lock',
  logout: 'leave',
  mail: 'communication-letter-memo-svgrepo-com',
  mapPin: 'office-pin-pushpin-svgrepo-com',
  megaphone: 'speaker',
  /** Building / org (LuBuilding2). */
  building2: 'factory',
  menu: 'list',
  /** Overflow / more (LuEllipsisVertical). */
  moreVertical: 'menu',
  messageCircle: 'comments',
  messageSquare: 'comments',
  moon: 'night_landscape',
  music: 'music',
  partyPopper: 'achievement-svgrepo-com',
  pencil: 'signature',
  phone: 'phone',
  play: 'start',
  plus: 'plus',
  puzzle: 'puzzle',
  refresh: 'refresh',
  rotateCw: 'refresh',
  save: 'collect',
  search: 'search',
  /** Send / submit (LuSendHorizontal). */
  send: 'advance',
  settings: 'settings',
  share: 'share',
  shield: 'safe',
  shieldCheck: 'data_protection',
  smartphone: 'touchscreen_smartphone',
  sparkles: 'idea',
  sprout: 'biomass',
  star: 'rating',
  /** Stop / square control (LuSquare). */
  stopSquare: 'cancel',
  trash: 'empty_trash',
  trendingUp: 'branch-growth-invest-svgrepo-com',
  trophy: 'certificate-svgrepo-com',
  timeline: 'timeline',
  /** Thread / conversation header (LuMessageSquareText). */
  messageSquareText: 'comments',
  thumbsUp: 'like',
  upload: 'upload',
  user: 'contacts',
  userPlus: 'invite',
  users: 'organization',
  video: 'video_file',
  zap: 'electricity',
} as const satisfies Record<string, IconName>;

export type UiIconKey = keyof typeof uiIcons;
