/** Auto-generated by `node scripts/generate-icon-map.mjs`. Do not edit manually. */

import iconDoodleBell from './assets/doodle_bell.svg?url';
import iconDoodleBook from './assets/doodle_book.svg?url';
import iconDoodleBookOpen from './assets/doodle_book_open.svg?url';
import iconDoodleBot from './assets/doodle_bot.svg?url';
import iconDoodleCake from './assets/doodle_cake.svg?url';
import iconDoodleCalendar from './assets/doodle_calendar.svg?url';
import iconDoodleCamera from './assets/doodle_camera.svg?url';
import iconDoodleCaution from './assets/doodle_caution.svg?url';
import iconDoodleChecklist from './assets/doodle_checklist.svg?url';
import iconDoodleClock from './assets/doodle_clock.svg?url';
import iconDoodleCollab from './assets/doodle_collab.svg?url';
import iconDoodleCookie from './assets/doodle_cookie.svg?url';
import iconDoodleCrown from './assets/doodle_crown.svg?url';
import iconDoodleDashboard from './assets/doodle_dashboard.svg?url';
import iconDoodleDiamond from './assets/doodle_diamond.svg?url';
import iconDoodleExternal from './assets/doodle_external.svg?url';
import iconDoodleEye from './assets/doodle_eye.svg?url';
import iconDoodleFile from './assets/doodle_file.svg?url';
import iconDoodleFire from './assets/doodle_fire.svg?url';
import iconDoodleGift from './assets/doodle_gift.svg?url';
import iconDoodleGlobe from './assets/doodle_globe.svg?url';
import iconDoodleGrid from './assets/doodle_grid.svg?url';
import iconDoodleHeart from './assets/doodle_heart.svg?url';
import iconDoodleHome from './assets/doodle_home.svg?url';
import iconDoodleInfo from './assets/doodle_info.svg?url';
import iconDoodleLink from './assets/doodle_link.svg?url';
import iconDoodleList from './assets/doodle_list.svg?url';
import iconDoodleLocationpin from './assets/doodle_locationpin.svg?url';
import iconDoodleLock from './assets/doodle_lock.svg?url';
import iconDoodleLogout from './assets/doodle_logout.svg?url';
import iconDoodleMail from './assets/doodle_mail.svg?url';
import iconDoodleMegaphone from './assets/doodle_megaphone.svg?url';
import iconDoodleMessage from './assets/doodle_message.svg?url';
import iconDoodleMicroscope from './assets/doodle_microscope.svg?url';
import iconDoodleMoon from './assets/doodle_moon.svg?url';
import iconDoodleMusic from './assets/doodle_music.svg?url';
import iconDoodlePencil from './assets/doodle_pencil.svg?url';
import iconDoodlePencilRuler from './assets/doodle_pencil_ruler.svg?url';
import iconDoodlePhone from './assets/doodle_phone.svg?url';
import iconDoodlePhoneSmart from './assets/doodle_phone_smart.svg?url';
import iconDoodlePlant from './assets/doodle_plant.svg?url';
import iconDoodlePuzzle from './assets/doodle_puzzle.svg?url';
import iconDoodleSend from './assets/doodle_send.svg?url';
import iconDoodleShare from './assets/doodle_share.svg?url';
import iconDoodleShield from './assets/doodle_shield.svg?url';
import iconDoodleShieldCheck from './assets/doodle_shield_check.svg?url';
import iconDoodleSparkles from './assets/doodle_sparkles.svg?url';
import iconDoodleSpeaker from './assets/doodle_speaker.svg?url';
import iconDoodleStar from './assets/doodle_star.svg?url';
import iconDoodleTick from './assets/doodle_tick.svg?url';
import iconDoodleTickCircle from './assets/doodle_tick_circle.svg?url';
import iconDoodleTree from './assets/doodle_tree.svg?url';
import iconDoodleTrophy from './assets/doodle_trophy.svg?url';
import iconDoodleUser from './assets/doodle_user.svg?url';
import iconDoodleUsers from './assets/doodle_users.svg?url';
import iconDoodleVideocamera from './assets/doodle_videocamera.svg?url';

export const iconUrls = {
  'doodle_bell': iconDoodleBell,
  'doodle_book': iconDoodleBook,
  'doodle_book_open': iconDoodleBookOpen,
  'doodle_bot': iconDoodleBot,
  'doodle_cake': iconDoodleCake,
  'doodle_calendar': iconDoodleCalendar,
  'doodle_camera': iconDoodleCamera,
  'doodle_caution': iconDoodleCaution,
  'doodle_checklist': iconDoodleChecklist,
  'doodle_clock': iconDoodleClock,
  'doodle_collab': iconDoodleCollab,
  'doodle_cookie': iconDoodleCookie,
  'doodle_crown': iconDoodleCrown,
  'doodle_dashboard': iconDoodleDashboard,
  'doodle_diamond': iconDoodleDiamond,
  'doodle_external': iconDoodleExternal,
  'doodle_eye': iconDoodleEye,
  'doodle_file': iconDoodleFile,
  'doodle_fire': iconDoodleFire,
  'doodle_gift': iconDoodleGift,
  'doodle_globe': iconDoodleGlobe,
  'doodle_grid': iconDoodleGrid,
  'doodle_heart': iconDoodleHeart,
  'doodle_home': iconDoodleHome,
  'doodle_info': iconDoodleInfo,
  'doodle_link': iconDoodleLink,
  'doodle_list': iconDoodleList,
  'doodle_locationpin': iconDoodleLocationpin,
  'doodle_lock': iconDoodleLock,
  'doodle_logout': iconDoodleLogout,
  'doodle_mail': iconDoodleMail,
  'doodle_megaphone': iconDoodleMegaphone,
  'doodle_message': iconDoodleMessage,
  'doodle_microscope': iconDoodleMicroscope,
  'doodle_moon': iconDoodleMoon,
  'doodle_music': iconDoodleMusic,
  'doodle_pencil': iconDoodlePencil,
  'doodle_pencil_ruler': iconDoodlePencilRuler,
  'doodle_phone': iconDoodlePhone,
  'doodle_phone_smart': iconDoodlePhoneSmart,
  'doodle_plant': iconDoodlePlant,
  'doodle_puzzle': iconDoodlePuzzle,
  'doodle_send': iconDoodleSend,
  'doodle_share': iconDoodleShare,
  'doodle_shield': iconDoodleShield,
  'doodle_shield_check': iconDoodleShieldCheck,
  'doodle_sparkles': iconDoodleSparkles,
  'doodle_speaker': iconDoodleSpeaker,
  'doodle_star': iconDoodleStar,
  'doodle_tick': iconDoodleTick,
  'doodle_tick_circle': iconDoodleTickCircle,
  'doodle_tree': iconDoodleTree,
  'doodle_trophy': iconDoodleTrophy,
  'doodle_user': iconDoodleUser,
  'doodle_users': iconDoodleUsers,
  'doodle_videocamera': iconDoodleVideocamera,
} as const;

export type IconName = keyof typeof iconUrls;
