/** Auto-generated by `node scripts/generate-icon-map.mjs`. Do not edit manually. */

import iconAchievementSvgrepoCom from './assets/achievement-svgrepo-com.svg?url';
import iconAddImage from './assets/add_image.svg?url';
import iconAdvance from './assets/advance.svg?url';
import iconAlarmClock from './assets/alarm_clock.svg?url';
import iconAlphabeticalSortingAz from './assets/alphabetical_sorting_az.svg?url';
import iconApproval from './assets/approval.svg?url';
import iconApprove from './assets/approve.svg?url';
import iconAssistant from './assets/assistant.svg?url';
import iconBadDecision from './assets/bad_decision.svg?url';
import iconBagCashCurrencySvgrepoCom from './assets/bag-cash-currency-svgrepo-com.svg?url';
import iconBaristaSvgrepoCom from './assets/barista-svgrepo-com.svg?url';
import iconBiohazard from './assets/biohazard.svg?url';
import iconBiomass from './assets/biomass.svg?url';
import iconBiotech from './assets/biotech.svg?url';
import iconBirthdayCakeSvgrepoCom from './assets/birthday-cake-svgrepo-com.svg?url';
import iconBookSvgrepoCom from './assets/book-svgrepo-com.svg?url';
import iconBranchGrowthInvestSvgrepoCom from './assets/branch-growth-invest-svgrepo-com.svg?url';
import iconCalendar from './assets/calendar.svg?url';
import iconCamera from './assets/camera.svg?url';
import iconCancel from './assets/cancel.svg?url';
import iconCellPhone from './assets/cell_phone.svg?url';
import iconCertificateSvgrepoCom from './assets/certificate-svgrepo-com.svg?url';
import iconChartDiagramPieSvgrepoCom from './assets/chart-diagram-pie-svgrepo-com.svg?url';
import iconChartGrowthInvestSvgrepoCom from './assets/chart-growth-invest-svgrepo-com.svg?url';
import iconCheckMoneyOrderSvgrepoCom from './assets/check-money-order-svgrepo-com.svg?url';
import iconCheckmark from './assets/checkmark.svg?url';
import iconClapperboard from './assets/clapperboard.svg?url';
import iconClockSvgrepoCom from './assets/clock-svgrepo-com.svg?url';
import iconClock from './assets/clock.svg?url';
import iconCloth from './assets/cloth.svg?url';
import iconCollaboration from './assets/collaboration.svg?url';
import iconCollect from './assets/collect.svg?url';
import iconComments from './assets/comments.svg?url';
import iconCommunicationLetterMemoSvgrepoCom from './assets/communication-letter-memo-svgrepo-com.svg?url';
import iconContacts from './assets/contacts.svg?url';
import iconCrystalOscillator from './assets/crystal_oscillator.svg?url';
import iconCurrencyExchange from './assets/currency_exchange.svg?url';
import iconCustomerSupport from './assets/customer_support.svg?url';
import iconDataProtection from './assets/data_protection.svg?url';
import iconDepartment from './assets/department.svg?url';
import iconDiploma1 from './assets/diploma_1.svg?url';
import iconDisapprove from './assets/disapprove.svg?url';
import iconDisclaimer from './assets/disclaimer.svg?url';
import iconDocument from './assets/document.svg?url';
import iconDonate from './assets/donate.svg?url';
import iconDown from './assets/down.svg?url';
import iconDownload from './assets/download.svg?url';
import iconELearningSvgrepoCom from './assets/e-learning-svgrepo-com.svg?url';
import iconEditImage from './assets/edit_image.svg?url';
import iconElectricity from './assets/electricity.svg?url';
import iconEmptyTrash from './assets/empty_trash.svg?url';
import iconExternal from './assets/external.svg?url';
import iconFactory from './assets/factory.svg?url';
import iconFeedback from './assets/feedback.svg?url';
import iconFile from './assets/file.svg?url';
import iconFilledFilter from './assets/filled_filter.svg?url';
import iconGlobeSvgrepoCom from './assets/globe-svgrepo-com.svg?url';
import iconGoogle from './assets/google.svg?url';
import iconGraduationCap from './assets/graduation_cap.svg?url';
import iconGrid from './assets/grid.svg?url';
import iconHeadset from './assets/headset.svg?url';
import iconHome from './assets/home.svg?url';
import iconIdea from './assets/idea.svg?url';
import iconInfo from './assets/info.svg?url';
import iconInspection from './assets/inspection.svg?url';
import iconInvite from './assets/invite.svg?url';
import iconKnowledgeSvgrepoCom from './assets/knowledge-svgrepo-com.svg?url';
import iconLeave from './assets/leave.svg?url';
import iconLeft from './assets/left.svg?url';
import iconLibrary from './assets/library.svg?url';
import iconLike from './assets/like.svg?url';
import iconLink from './assets/link.svg?url';
import iconList from './assets/list.svg?url';
import iconLock from './assets/lock.svg?url';
import iconMenu from './assets/menu.svg?url';
import iconMindMap from './assets/mind_map.svg?url';
import iconMusic from './assets/music.svg?url';
import iconNegativeDynamic from './assets/negative_dynamic.svg?url';
import iconNightLandscape from './assets/night_landscape.svg?url';
import iconOfficePinPushpinSvgrepoCom from './assets/office-pin-pushpin-svgrepo-com.svg?url';
import iconOk from './assets/ok.svg?url';
import iconOrganization from './assets/organization.svg?url';
import iconPhone from './assets/phone.svg?url';
import iconPlus from './assets/plus.svg?url';
import iconPodiumWithSpeaker from './assets/podium_with_speaker.svg?url';
import iconPodiumWithoutSpeaker from './assets/podium_without_speaker.svg?url';
import iconPositiveDynamic from './assets/positive_dynamic.svg?url';
import iconPuzzle from './assets/puzzle.svg?url';
import iconQuestions from './assets/questions.svg?url';
import iconQuizSvgrepoCom from './assets/quiz-svgrepo-com.svg?url';
import iconRating from './assets/rating.svg?url';
import iconReadingSvgrepoCom from './assets/reading-svgrepo-com.svg?url';
import iconReading from './assets/reading.svg?url';
import iconReadingEbook from './assets/reading_ebook.svg?url';
import iconRefresh from './assets/refresh.svg?url';
import iconRight from './assets/right.svg?url';
import iconSafe from './assets/safe.svg?url';
import iconSchoolSvgrepoCom from './assets/school-svgrepo-com.svg?url';
import iconSearch from './assets/search.svg?url';
import iconSerialTasks from './assets/serial_tasks.svg?url';
import iconSettings from './assets/settings.svg?url';
import iconShare from './assets/share.svg?url';
import iconSignature from './assets/signature.svg?url';
import iconSpeaker from './assets/speaker.svg?url';
import iconStart from './assets/start.svg?url';
import iconStatistics from './assets/statistics.svg?url';
import iconSynchronize from './assets/synchronize.svg?url';
import iconTemplate from './assets/template.svg?url';
import iconTimeline from './assets/timeline.svg?url';
import iconTodoList from './assets/todo_list.svg?url';
import iconTouchscreenSmartphone from './assets/touchscreen_smartphone.svg?url';
import iconTreeStructure from './assets/tree_structure.svg?url';
import iconUp from './assets/up.svg?url';
import iconUpRight from './assets/up_right.svg?url';
import iconUpload from './assets/upload.svg?url';
import iconVideoCoursesSvgrepoCom from './assets/video-courses-svgrepo-com.svg?url';
import iconVideoFile from './assets/video_file.svg?url';
import iconViewDetails from './assets/view_details.svg?url';
import iconVip from './assets/vip.svg?url';
import iconVoicePresentation from './assets/voice_presentation.svg?url';
import iconWebinarSvgrepoCom from './assets/webinar-svgrepo-com.svg?url';
import iconWorkflow from './assets/workflow.svg?url';

export const iconUrls = {
  'achievement-svgrepo-com': iconAchievementSvgrepoCom,
  'add_image': iconAddImage,
  'advance': iconAdvance,
  'alarm_clock': iconAlarmClock,
  'alphabetical_sorting_az': iconAlphabeticalSortingAz,
  'approval': iconApproval,
  'approve': iconApprove,
  'assistant': iconAssistant,
  'bad_decision': iconBadDecision,
  'bag-cash-currency-svgrepo-com': iconBagCashCurrencySvgrepoCom,
  'barista-svgrepo-com': iconBaristaSvgrepoCom,
  'biohazard': iconBiohazard,
  'biomass': iconBiomass,
  'biotech': iconBiotech,
  'birthday-cake-svgrepo-com': iconBirthdayCakeSvgrepoCom,
  'book-svgrepo-com': iconBookSvgrepoCom,
  'branch-growth-invest-svgrepo-com': iconBranchGrowthInvestSvgrepoCom,
  'calendar': iconCalendar,
  'camera': iconCamera,
  'cancel': iconCancel,
  'cell_phone': iconCellPhone,
  'certificate-svgrepo-com': iconCertificateSvgrepoCom,
  'chart-diagram-pie-svgrepo-com': iconChartDiagramPieSvgrepoCom,
  'chart-growth-invest-svgrepo-com': iconChartGrowthInvestSvgrepoCom,
  'check-money-order-svgrepo-com': iconCheckMoneyOrderSvgrepoCom,
  'checkmark': iconCheckmark,
  'clapperboard': iconClapperboard,
  'clock-svgrepo-com': iconClockSvgrepoCom,
  'clock': iconClock,
  'cloth': iconCloth,
  'collaboration': iconCollaboration,
  'collect': iconCollect,
  'comments': iconComments,
  'communication-letter-memo-svgrepo-com': iconCommunicationLetterMemoSvgrepoCom,
  'contacts': iconContacts,
  'crystal_oscillator': iconCrystalOscillator,
  'currency_exchange': iconCurrencyExchange,
  'customer_support': iconCustomerSupport,
  'data_protection': iconDataProtection,
  'department': iconDepartment,
  'diploma_1': iconDiploma1,
  'disapprove': iconDisapprove,
  'disclaimer': iconDisclaimer,
  'document': iconDocument,
  'donate': iconDonate,
  'down': iconDown,
  'download': iconDownload,
  'e-learning-svgrepo-com': iconELearningSvgrepoCom,
  'edit_image': iconEditImage,
  'electricity': iconElectricity,
  'empty_trash': iconEmptyTrash,
  'external': iconExternal,
  'factory': iconFactory,
  'feedback': iconFeedback,
  'file': iconFile,
  'filled_filter': iconFilledFilter,
  'globe-svgrepo-com': iconGlobeSvgrepoCom,
  'google': iconGoogle,
  'graduation_cap': iconGraduationCap,
  'grid': iconGrid,
  'headset': iconHeadset,
  'home': iconHome,
  'idea': iconIdea,
  'info': iconInfo,
  'inspection': iconInspection,
  'invite': iconInvite,
  'knowledge-svgrepo-com': iconKnowledgeSvgrepoCom,
  'leave': iconLeave,
  'left': iconLeft,
  'library': iconLibrary,
  'like': iconLike,
  'link': iconLink,
  'list': iconList,
  'lock': iconLock,
  'menu': iconMenu,
  'mind_map': iconMindMap,
  'music': iconMusic,
  'negative_dynamic': iconNegativeDynamic,
  'night_landscape': iconNightLandscape,
  'office-pin-pushpin-svgrepo-com': iconOfficePinPushpinSvgrepoCom,
  'ok': iconOk,
  'organization': iconOrganization,
  'phone': iconPhone,
  'plus': iconPlus,
  'podium_with_speaker': iconPodiumWithSpeaker,
  'podium_without_speaker': iconPodiumWithoutSpeaker,
  'positive_dynamic': iconPositiveDynamic,
  'puzzle': iconPuzzle,
  'questions': iconQuestions,
  'quiz-svgrepo-com': iconQuizSvgrepoCom,
  'rating': iconRating,
  'reading-svgrepo-com': iconReadingSvgrepoCom,
  'reading': iconReading,
  'reading_ebook': iconReadingEbook,
  'refresh': iconRefresh,
  'right': iconRight,
  'safe': iconSafe,
  'school-svgrepo-com': iconSchoolSvgrepoCom,
  'search': iconSearch,
  'serial_tasks': iconSerialTasks,
  'settings': iconSettings,
  'share': iconShare,
  'signature': iconSignature,
  'speaker': iconSpeaker,
  'start': iconStart,
  'statistics': iconStatistics,
  'synchronize': iconSynchronize,
  'template': iconTemplate,
  'timeline': iconTimeline,
  'todo_list': iconTodoList,
  'touchscreen_smartphone': iconTouchscreenSmartphone,
  'tree_structure': iconTreeStructure,
  'up': iconUp,
  'up_right': iconUpRight,
  'upload': iconUpload,
  'video-courses-svgrepo-com': iconVideoCoursesSvgrepoCom,
  'video_file': iconVideoFile,
  'view_details': iconViewDetails,
  'vip': iconVip,
  'voice_presentation': iconVoicePresentation,
  'webinar-svgrepo-com': iconWebinarSvgrepoCom,
  'workflow': iconWorkflow,
} as const;

export type IconName = keyof typeof iconUrls;
